### PR TITLE
do not raise exception on failed bandit

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

#39 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Instead of raising error, we should check for errors during `si-aggregate` and `graph-sync` so that we don't repeatedly schedule for packages which we cannot solve.

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
Thanks!! :100:

**Comment by goern** [comment]
@KPostOffice is this still on hold?

**Comment by KPostOffice** [comment]
Still waiting on:
https://github.com/thoth-station/storages/pull/2054
and
https://github.com/thoth-station/si-aggregator/pull/35/files

**Pull request merged**
