### PR TITLE
add pre-commit config

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

This is the same config found in `common`

### CODE REVIEW

**Review by fridex — APPROVED** [review]
lgtm :+1:

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
so we can not gate with only a noop job...

**Comment by goern** [comment]
regate

**Pull request merged**
