### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :100:

**Comment by bissenbay** [comment]
@harshad16 made changes here as well

**Comment by bissenbay** [comment]
@fridex @harshad16 PTAL

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :100:

**Review by pacospace — APPROVED** [review]

**Pull request merged**
